package com.example.mediscannerai.presentation.settings

import android.content.Intent
import android.provider.Settings
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.selection.selectable
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.Info
import androidx.compose.material.icons.filled.Lock
import androidx.compose.material.icons.filled.Notifications
import androidx.compose.material.icons.filled.Refresh
import androidx.compose.material.icons.filled.Warning
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.semantics.Role
import androidx.compose.ui.unit.dp
import com.example.mediscannerai.BuildConfig
import com.example.mediscannerai.data.local.AppSettings
import com.example.mediscannerai.data.local.PrivacyPrefs
import com.example.mediscannerai.data.local.ThemeMode

private enum class InfoPopup { Disclaimer, Privacy, About }

private const val DISCLAIMER_TEXT =
    "MediScanner AI is an educational tool. It explains what is written on a lab " +
            "report in simple language.\n\n" +
            "It does NOT diagnose any condition, recommend or change any treatment or " +
            "medicine, replace your doctor, or give definite medical conclusions.\n\n" +
            "Text is read from your report automatically and explanations are generated by " +
            "an AI service. Both can contain mistakes, so always check against your original " +
            "report.\n\n" +
            "Always discuss your results, and any medicine you take, with a qualified " +
            "healthcare professional. In an emergency, contact your local emergency number."

private const val PRIVACY_TEXT =
    "Your reports\n" +
            "Saved reports (the text, explanation and questions) are stored only in this " +
            "app's private storage on your phone. Cloud backup of the app is turned off. " +
            "There is no sign-in. Deleting a report in History removes it from your phone.\n\n" +
            "What is sent over the internet\n" +
            "To explain a report or generate doctor questions, the report's text is sent to " +
            "an online AI service (Groq). The app first removes details such as names, ID " +
            "numbers, phone numbers, emails and address lines. This is automatic and can " +
            "miss things, which is why you see a preview before the first request.\n" +
            "Medicine names you type in Medicine Information are also sent to the same service.\n\n" +
            "On your phone only\n" +
            "Reading text from photos and PDFs happens on your device. Temporary copies of " +
            "report images are deleted after the text is read. Health Trends are built from " +
            "your saved reports on your phone.\n\n" +
            "Your choice\n" +
            "You can show the AI privacy notice again from this Settings screen."

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun SettingsScreen(onBack: () -> Unit) {
    val context = LocalContext.current
    val themeMode = AppSettings.themeMode
    var popup by remember { mutableStateOf<InfoPopup?>(null) }
    var noticeReset by remember { mutableStateOf(false) }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Settings") },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back")
                    }
                }
            )
        }
    ) { innerPadding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(innerPadding)
                .verticalScroll(rememberScrollState())
        ) {
            SectionHeader("Appearance")
            ThemeOption("Follow system", themeMode == ThemeMode.System) {
                AppSettings.setThemeMode(context, ThemeMode.System)
            }
            ThemeOption("Light", themeMode == ThemeMode.Light) {
                AppSettings.setThemeMode(context, ThemeMode.Light)
            }
            ThemeOption("Dark", themeMode == ThemeMode.Dark) {
                AppSettings.setThemeMode(context, ThemeMode.Dark)
            }

            HorizontalDivider(modifier = Modifier.padding(vertical = 8.dp))

            SectionHeader("Notifications")
            ListItem(
                headlineContent = { Text("Notification settings") },
                supportingContent = {
                    Text("Open your phone's settings for this app. Medicine reminders will use these.")
                },
                leadingContent = { Icon(Icons.Default.Notifications, contentDescription = null) },
                modifier = Modifier.clickable {
                    val intent = Intent(Settings.ACTION_APP_NOTIFICATION_SETTINGS)
                        .putExtra(Settings.EXTRA_APP_PACKAGE, context.packageName)
                    context.startActivity(intent)
                }
            )

            HorizontalDivider(modifier = Modifier.padding(vertical = 8.dp))

            SectionHeader("Privacy and information")
            ListItem(
                headlineContent = { Text("Privacy information") },
                supportingContent = { Text("How your reports are stored and what is sent online") },
                leadingContent = { Icon(Icons.Default.Lock, contentDescription = null) },
                modifier = Modifier.clickable { popup = InfoPopup.Privacy }
            )
            ListItem(
                headlineContent = { Text("Show the AI privacy notice again") },
                supportingContent = {
                    Text(
                        if (noticeReset) {
                            "Done. The notice will appear before your next explanation."
                        } else {
                            "Shows the preview of what is sent before the next explanation"
                        }
                    )
                },
                leadingContent = { Icon(Icons.Default.Refresh, contentDescription = null) },
                modifier = Modifier.clickable {
                    PrivacyPrefs.clearAiNoticeAccepted(context)
                    noticeReset = true
                }
            )
            ListItem(
                headlineContent = { Text("Medical disclaimer") },
                supportingContent = { Text("What this app can and cannot do") },
                leadingContent = { Icon(Icons.Default.Warning, contentDescription = null) },
                modifier = Modifier.clickable { popup = InfoPopup.Disclaimer }
            )
            ListItem(
                headlineContent = { Text("About MediScanner AI") },
                supportingContent = { Text("Version ${BuildConfig.VERSION_NAME}") },
                leadingContent = { Icon(Icons.Default.Info, contentDescription = null) },
                modifier = Modifier.clickable { popup = InfoPopup.About }
            )
        }
    }

    when (popup) {
        InfoPopup.Disclaimer -> InfoDialog("Medical disclaimer", DISCLAIMER_TEXT) { popup = null }
        InfoPopup.Privacy -> InfoDialog("Privacy information", PRIVACY_TEXT) { popup = null }
        InfoPopup.About -> InfoDialog(
            "About MediScanner AI",
            "MediScanner AI helps you read your lab reports in plain language.\n\n" +
                    "Version ${BuildConfig.VERSION_NAME}\n\n" +
                    "Text is read from your report on your device with Google ML Kit. " +
                    "Explanations and doctor questions are generated by an AI service. " +
                    "Built with Kotlin and Jetpack Compose.\n\n" +
                    "This app is educational only and is not a substitute for professional " +
                    "medical advice."
        ) { popup = null }
        null -> {}
    }
}

@Composable
private fun SectionHeader(title: String) {
    Text(
        title,
        style = MaterialTheme.typography.titleSmall,
        color = MaterialTheme.colorScheme.primary,
        modifier = Modifier.padding(start = 16.dp, top = 16.dp, end = 16.dp, bottom = 4.dp)
    )
}

@Composable
private fun ThemeOption(label: String, selected: Boolean, onSelect: () -> Unit) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .selectable(selected = selected, onClick = onSelect, role = Role.RadioButton)
            .padding(horizontal = 16.dp, vertical = 12.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        RadioButton(selected = selected, onClick = null)
        Spacer(modifier = Modifier.width(16.dp))
        Text(label, style = MaterialTheme.typography.bodyLarge)
    }
}

@Composable
private fun InfoDialog(title: String, text: String, onDismiss: () -> Unit) {
    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text(title) },
        text = {
            Column(modifier = Modifier.verticalScroll(rememberScrollState())) {
                Text(text, style = MaterialTheme.typography.bodyMedium)
            }
        },
        confirmButton = {
            TextButton(onClick = onDismiss) { Text("Close") }
        }
    )
}